name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential
    - name: Configure CMake
      run: cmake -S server -B server/build
    - name: Build GameServer
      run: cmake --build server/build
    - name: Run C Unit Tests
      run: cd server/build && ctest --output-on-failure

  build-and-test-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Python Dependencies
      run: |
        python -m venv client/venv
        source client/venv/bin/activate
        pip install -r client/requirements.txt
    - name: Run Python Backend Unit Tests
      run: |
        source client/venv/bin/activate
        pytest client/tests/test_backend.py

  integration-tests:
    runs-on: ubuntu-latest
    needs: [build-and-test-server, build-and-test-client]
    steps:
    - uses: actions/checkout@v3
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Python Dependencies
      run: |
        python -m venv client/venv
        source client/venv/bin/activate
        pip install -r client/requirements.txt
    - name: Build GameServer
      run: cmake --build server/build
    - name: Start GameServer in background
      run: |
        cd server/build
        ./GameServer & # Assuming executable name is GameServer
        echo "GameServer started in background."
        sleep 5 # Give server time to start
      shell: bash
    - name: Start GameClient Backend in background
      run: |
        source client/venv/bin/activate
        python client/backend/app.py &
        echo "GameClient Backend started in background."
        sleep 5 # Give backend time to start
      shell: bash
    - name: Run Integration Tests
      run: |
        source client/venv/bin/activate
        # Placeholder for actual integration test command
        # This would involve Python scripts that connect to both server and client
        echo "Running integration tests..."
        # Example: python client/tests/run_integration_tests.py
